_uniforms = [
	"USP_G3C_CU_KP_MC",
	"USP_G3C_CU_KP_MX_MC",
	"USP_G3C_CS_CU_KP_MC",
	"USP_G3C_CS_CU_KP_MX_MC",
	"USP_G3C_RS_CU_KP_MC",
	"USP_G3C_RS_CU_KP_MX_MC",
	"USP_G3C_RS2_CU_KP_MC",
	"USP_G3C_RS2_CU_KP_MX_MC"
];
_uniformsHelicopter = [
	"USP_G3C_CU_KP_GRY",
	"USP_G3C_CU_KP_KHK",
	"USP_G3C_CU_KP_RGR"
];
_uniformsFixedWing = [
	"CSU13BPTan_Base_NG",
	"CSU13BP_Base_NG",
	"CSU15BPTan_Base_FG",
	"CSU15BP_Base_FG"
];
_uniformsLowVis = [

];
_vestsLeader = [
	"Crye_AVS_MC_TeamLeader_1_NC_NoBelt",
	"Crye_AVS_MC_TeamLeader_1_NC",
	"Crye_AVS_MC_TeamLeader_4_NC_NoBelt",
	"Crye_AVS_MC_TeamLeader_4_NC",
	"Crye_AVS_MC_TeamLeader_7_NC_NoBelt",
	"Crye_AVS_MC_TeamLeader_7_NC"
];
_vestsComms = [
	"Crye_AVS_MC_Comms_1_NC_NoBelt",
	"Crye_AVS_MC_Comms_1_NC",
	"Crye_AVS_MC_Comms_4_NC_NoBelt",
	"Crye_AVS_MC_Comms_4_NC",
	"Crye_AVS_MC_Comms_7_NC_NoBelt",
	"Crye_AVS_MC_Comms_7_NC"
];
_vestsMedic = [
	"Crye_AVS_MC_Medic_1_NC_NoBelt",
	"Crye_AVS_MC_Medic_1_NC"
];
_vestsOperator = [
	"Crye_AVS_MC_1_NC_NoBelt",
	"Crye_AVS_MC_1_NC",
	"Crye_AVS_MC_4_NC_NoBelt",
	"Crye_AVS_MC_4_NC",
	"Crye_AVS_MC_7_NC_NoBelt",
	"Crye_AVS_MC_7_NC",
	"Crye_AVS_MC_10_NoBelt",
	"Crye_AVS_MC_10"
];
_vestsMachineGunner = [
	"Crye_AVS_MC_LMG_1_NC_NoBelt",
	"Crye_AVS_MC_LMG_1_NC"
];
_vestsHelicopter = [
	"Crye_AVS_BLK_Light_1_NC",
	"Crye_AVS_BLK_Light_3_NC",
	"Crye_AVS_CB_Light_1_NC",
	"Crye_AVS_CB_Light_3_NC",
	"Crye_AVS_MC_Light_1_NC",
	"Crye_AVS_MC_Light_3_NC",
	"Crye_AVS_RG_Light_1_NC",
	"Crye_AVS_RG_Light_3_NC"
];
_vestsFixedWing = [
	"SRU21P_LPU9P_PCU15AP",
	"SRU21P_LPU9P_PCU15AP_Alt",
	"SV2B_LPU23P",
	"SV2B_LPU36P"
];
_backpacksSmall = [
	"TFL_avs_pack_mc_flag",
	"TFL_avs_pack_mc_bolt_flag",
	"TFL_avs_pack_mc",
	"TFL_avs_pack_bolt_mc",
	"TFL_avs_pack_breacher_mc_flag",
	"TFL_avs_pack_breacher_mc",
	"TFL_avs_pack_mc_halligan_flag",
	"TFL_avs_pack_mc_halligan"
];
_backpacksMedic = [
	"TFL_M9Backpack_MC",
	"RATS"
];
_backpacksLarge = [
	"pmc_MysteryASAP_mc",
	"pmc_MysteryCL_mc",
	"TFL_LBT_day_mc"
];
_headgearLight = [

];
_headgearHeavy = [
	"USP_OPSCORE_FASTMTC_CG",
	"USP_OPSCORE_FASTMTC",
	"USP_OPSCORE_FASTMTC_C"
];
_headgearHelicopters = [
	"rhsusf_hgu56p_visor_black",
	"rhsusf_hgu56p_visor_mask_black",
	"rhsusf_hgu56p_visor_mask_Empire_black",
	"rhsusf_hgu56p_visor_mask_black_skull",
	"rhsusf_hgu56p_visor_mask_smiley",
	"rhsusf_hgu56p_visor_tan",
	"rhsusf_hgu56p_visor_mask_tan",
	"rhsusf_hgu56p_visor",
	"rhsusf_hgu56p_visor_mask",
	"rhsusf_hgu56p_visor_mask_mo",
	"rhsusf_hgu56p_visor_mask_skull",
	"rhsusf_ihadss"
];
_headgearFixedWing = [
	"HGU55P_MBU12P_Amber",
	"HGU55P_MBU12P_Clear",
	"HGU55P_MBU12P_Tinted",
	"JHMCS_MBU12P",
	"JHMCS_MBU14P",
	"JHMCS2_MBU12P",
	"JHMCS2_MBU20P",
	"JHMCS2_MBU20P",
	"JHMCS_MBU23P"
];
_facewear = [
	"USP_SOLR_AF_OAK",
	"USP_RAID_BLK2",
	"USP_RAID_BLK",
	"USP_RAID_SMB1_BLK2",
	"USP_RAID_SMB1_BLK",
	"USP_RAID_SMB3_BLK2",
	"USP_RAID_SMB3_BLK",
	"USP_RAID_SMC1_BLK2",
	"USP_RAID_SMC1_BLK",
	"USP_RAID_SMC3_BLK2",
	"USP_RAID_SMC3_BLK",
	"USP_RAID_SMG1_BLK2",
	"USP_RAID_SMG1_BLK",
	"USP_RAID_SMG3_BLK2",
	"USP_RAID_SMG3_BLK",
	"USP_RAID_SMW1_BLK2",
	"USP_RAID_SMW1_BLK",
	"USP_RAID_SMW3_BLK2",
	"USP_RAID_SMW3_BLK",
	"USP_RAID2_BLK2",
	"USP_RAID2_BLK",
	"USP_RAID2_SMB1_BLK2",
	"USP_RAID2_SMB1_BLK",
	"USP_RAID2_SMB3_BLK2",
	"USP_RAID2_SMB3_BLK",
	"USP_RAID2_SMC1_BLK2",
	"USP_RAID2_SMC1_BLK",
	"USP_RAID2_SMC3_BLK2",
	"USP_RAID2_SMC3_BLK",
	"USP_RAID2_SMG1_BLK2",
	"USP_RAID2_SMG1_BLK",
	"USP_RAID2_SMG3_BLK2",
	"USP_RAID2_SMG3_BLK",
	"USP_RAID2_SMW1_BLK2",
	"USP_RAID2_SMW1_BLK",
	"USP_RAID2_SMW3_BLK2",
	"USP_RAID2_SMW3_BLK",
	"USP_BALACLAVA_BLK",
	"USP_BALACLAVA_CBR",
	"USP_BALACLAVA_RGR",
	"USP_BALACLAVA2",
	"USP_BALACLAVA2_CBR",
	"USP_BALACLAVA2_RGR",
	"USP_BALACLAVA_ADV_BLK",
	"USP_BALACLAVA_ADV_BLK2",
	"USP_BALACLAVA_ADV_BLK3",
	"USP_BALACLAVA_ADV_CBR",
	"USP_BALACLAVA_ADV_CBR2",
	"USP_BALACLAVA_ADV_CBR3",
	"USP_BALACLAVA_ADV_RGR",
	"USP_BALACLAVA_ADV_RGR2",
	"USP_BALACLAVA_ADV_RGR3",
	"USP_BALACLAVA_ADV_SMC1_BLK",
	"USP_BALACLAVA_ADV_SMC1_BLK2",
	"USP_BALACLAVA_ADV_SMC1_BLK3",
	"USP_BALACLAVA_ADV_SMC1_CBR",
	"USP_BALACLAVA_ADV_SMC1_CBR2",
	"USP_BALACLAVA_ADV_SMC1_CBR3",
	"USP_BALACLAVA_ADV_SMC1_RGR",
	"USP_BALACLAVA_ADV_SMC1_RGR2",
	"USP_BALACLAVA_ADV_SMC1_RGR3",
	"USP_BALACLAVA_ADV_SMG1_BLK",
	"USP_BALACLAVA_ADV_SMG1_BLK2",
	"USP_BALACLAVA_ADV_SMG1_BLK3",
	"USP_BALACLAVA_ADV_SMG1_CBR",
	"USP_BALACLAVA_ADV_SMG1_CBR2",
	"USP_BALACLAVA_ADV_SMG1_CBR3",
	"USP_BALACLAVA_ADV_SMG1_RGR",
	"USP_BALACLAVA_ADV_SMG1_RGR2",
	"USP_BALACLAVA_ADV_SMG1_RGR3",
	"USP_BALACLAVA_ESS_BLK",
	"USP_BALACLAVA_ESS_CBR",
	"USP_BALACLAVA_ESS_RGR",
	"USP_BALACLAVA_ESS_SMB1_BLK",
	"USP_BALACLAVA_ESS_SMB1_CBR",
	"USP_BALACLAVA_ESS_SMB1_RGR",
	"USP_BALACLAVA_ESS_SMC1_BLK",
	"USP_BALACLAVA_ESS_SMC1_CBR",
	"USP_BALACLAVA_ESS_SMC1_RGR",
	"USP_BALACLAVA_ESS_SMG1_BLK",
	"USP_BALACLAVA_ESS_SMG1_CBR",
	"USP_BALACLAVA_ESS_SMG1_RGR",
	"USP_ADVANCER_CLR",
	"USP_ADVANCER_YEL",
	"USP_ADVANCER",
	"USP_ADVANCER_CLR_GU",
	"USP_ADVANCER_YEL_GU",
	"USP_ADVANCER_GU",
	"USP_ADVANCER_GU_SF2",
	"USP_ADVANCER_GU_SF3",
	"USP_ADVANCER_GU_SNL",
	"USP_ADVANCER_GU_SNL2",
	"USP_ADVANCER_GU_SNL3",
	"USP_ADVANCER_SF2",
	"USP_ADVANCER_SF3",
	"USP_ADVANCER_SL2",
	"USP_ADVANCER_SL3",
	"USP_ADVANCER_STL2",
	"USP_ADVANCER_STL3",
	"USP_FORETREX",
	"USP_DETCORD_BLK2",
	"USP_DETCORD_BLK",
	"USP_DETCORD_SMC1_BLK2",
	"USP_DETCORD_SMC1_BLK",
	"USP_DETCORD_SMC3_BLK2",
	"USP_DETCORD_SMC3_BLK",
	"USP_DETCORD_SMG1_BLK2",
	"USP_DETCORD_SMG1_BLK",
	"USP_DETCORD_SMG3_BLK",
	"USP_DETCORD_SMG3_BLK",
	"USP_STRAIGHTJACKET_BLK2",
	"USP_STRAIGHTJACKET_BLK",
	"USP_STRAIGHTJACKET_SMC1_BLK2",
	"USP_STRAIGHTJACKET_SMC1_BLK",
	"USP_STRAIGHTJACKET_SMC3_BLK2",
	"USP_STRAIGHTJACKET_SMC3_BLK",
	"USP_STRAIGHTJACKET_SMG1_BLK2",
	"USP_STRAIGHTJACKET_SMG1_BLK",
	"USP_STRAIGHTJACKET_SMG3_BLK",
	"USP_STRAIGHTJACKET_SMG3_BLK",
	"USP_SHEMAGH2_CBR",
	"USP_SHEMAGH2_RGR"
];
_NVGs = [
	"USP_PVS31",
	"USP_PVS31_COMPACT",
	"USP_PVS31_HIGH",
	"USP_PVS31_LOW"
];
_basicMedical = [
	"nzf_FAK",
	"kat_CaffeineItem",
	"kat_Pulseoximeter"
];
_advancedMedical = [
	"kat_accuvac",
	"nzf_Medikit",
	"kat_stethoscope",
	"kat_Pulseoximeter"
];
_drugs = [
	"kat_larynx",	
	"ACE_personalAidKit",	
	"kat_X_AED",
	"kat_AED",
	"kat_amiodarone",
	"kat_lidocaine",
	"kat_phenylephrine"
];
_ammo = [
	"121_2Rnd_Slug",
	"rhs_mag_20Rnd_SCAR_762x51_m61_ap",
	"rhs_mag_20Rnd_SCAR_762x51_m62_tracer",
	"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
	"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
	"rhs_mag_30Rnd_556x45_M855A1_PMAG",
	"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan",
	"Tier1_100Rnd_762x51_Belt_M61_AP",
	"Tier1_100Rnd_762x51_Belt_M62_Tracer",
	"rhsusf_100Rnd_762x51_m61_ap",
	"rhsusf_100Rnd_762x51_m62_tracer",
	"Tier1_250Rnd_762x51_Belt_M61_AP",
	"Tier1_250Rnd_762x51_Belt_M62_Tracer",
	"rhsusf_20Rnd_762x51_m118_special_Mag",
	"rhsusf_20Rnd_762x51_m62_Mag",
	"rhsusf_20Rnd_762x51_m993_Mag",
	"rhsusf_200Rnd_556x45_soft_pouch_coyote",
	"rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",
	"rhsusf_20Rnd_762x51_SR25_m993_Mag",
	"rhsusf_20Rnd_762x51_SR25_m62_Mag"
];
_throwablesExplosives = [
	"ACE_Chemlight_HiBlue",
	"ACE_Chemlight_HiGreen",
	"ACE_Chemlight_HiRed",
	"ACE_Chemlight_HiWhite",
	"ACE_Chemlight_HiYellow",
	"ACE_Chemlight_IR",
	"ACE_HandFlare_Green",
	"ACE_HandFlare_Red",
	"ACE_HandFlare_White",
	"ACE_HandFlare_Yellow",
	"ACE_M84",
	"rhs_mag_an_m8hc",
	"rhs_mag_m18_green",
	"rhs_mag_m18_purple",
	"rhs_mag_m18_red",
	"rhs_mag_m18_yellow",
	"rhs_mag_m67",
	"MS_Strobe_Mag_1",
	"rhsusf_m112_mag",
	"rhsusf_m112x4_mag"
];
_pistols = [

];
_rifles = [
	"rhs_weap_SCARH_FDE_CQC",
	"rhs_weap_SCARH_FDE_STD",
	"rhs_weap_m4a1_blockII_bk",
	"rhs_weap_m4a1_blockII_KAC_bk",
	"rhs_weap_m4a1_blockII_d",
	"rhs_weap_m4a1_blockII_KAC_d"		
];
_riflesGrenadier = [
	"rhs_weap_m4a1_blockII_M203_bk",
	"rhs_weap_m4a1_blockII_M203_d"
];
_marksmanRiflesAndScopes = [
	"rhs_weap_sr25_ec",
	"rhs_weap_sr25_ec_d",
	"rhsusf_acc_m8541",
	"rhsusf_acc_m8541_d",
	"rhsgref_sdn6_suppressor"
];
_machineGuns = [
	"Tier1_MK46_Mod1_Savit",
	"Tier1_MK46_Mod1_Savit_Desert",
	"rhs_weap_m240B"
];
_launchers = [
	"launch_MRAWS_green_F",
	"MRAWS_HE_F",
	"MRAWS_HEAT55_F",
	"MRAWS_HEAT_F",
	"rhs_weap_m72a7",
	"rhs_weap_M136",
	"rhs_weap_M136_hedp",
	"rhs_weap_M136_hp"
];
_optics = [
	"rhsusf_acc_eotech",
	"rhsusf_acc_su230a_c",
	"rhsusf_acc_su230a_mrds_c",
	"rhsusf_acc_acog2_usmc",
	"rhsusf_acc_eotech_552",
	"rhsusf_acc_eotech_xps3"
];
_attachments = [
	"Tier1_M4BII_LA5_Top",
	"Tier1_M4BII_LA5_Side",
	"Tier1_M4BII_LA5_M300C",
	"Tier1_M4BII_LA5_M300C_FL",
	"Tier1_M4BII_LA5_M300C_Black",
	"Tier1_M4BII_LA5_M300C_Black_FL",
	"Tier1_M4BII_LA5_M600V",
	"Tier1_M4BII_LA5_M600V_FL",
	"Tier1_M4BII_LA5_M600V_Black",
	"Tier1_M4BII_LA5_M600V_Black_FL",
	"Tier1_M4BII_LA5_M603V",
	"Tier1_M4BII_LA5_M603V_FL",
	"Tier1_M4BII_NGAL_Top",
	"Tier1_M4BII_NGAL_Side",
	"Tier1_M4BII_NGAL_M300C",
	"Tier1_M4BII_NGAL_M300C_FL",
	"Tier1_M4BII_NGAL_M300C_Black",
	"Tier1_M4BII_NGAL_M300C_Black_FL",
	"Tier1_M4BII_NGAL_M600V",
	"Tier1_M4BII_NGAL_M600V_FL",
	"Tier1_M4BII_NGAL_M600V_Black",
	"Tier1_M4BII_NGAL_M600V_Black_FL",
	"Tier1_M4BII_NGAL_M603V",
	"Tier1_M4BII_NGAL_M603V_FL",
	"tier1_harris_bipod_rvg_mlok_tan",
	"tier1_harris_bipod_rvg_mlok_black",
	"tier1_harris_bipod_kac_mlok_tan",
	"tier1_harris_bipod_kac_mlok_black",
	"tier1_harris_bipod_mlok_tan",
	"tier1_harris_bipod_mlok_black_2",
	"tier1_harris_bipod_dd_mlok_tan",
	"tier1_harris_bipod_dd_mlok_black",
	"rhsusf_acc_grip2",
	"rhsusf_acc_grip2_tan",
	"rhsusf_acc_harris_bipod",
	"tier1_harris_bipod_tan",
	"tier1_harris_bipod_black",
	"rhsusf_acc_tdstubby_blk",
	"rhsusf_acc_tdstubby_tan",
	"tier1_harris_bipod_kac_black",
	"tier1_harris_bipod_kac_tan",
	"Tier1_DD_VFG_Black",
    "Tier1_Larue_FUG_Black",
    "Tier1_Larue_FUG_Tan",
	"Tier1_Larue_FUG_UDE",
	"Tier1_KAC_VFG_DE",
	"Tier1_KAC_VFG_Black",
	"Tier1_Gangster_Grip_Black",
	"Tier1_Gangster_Grip_Tan",
	"Tier1_GripPod_Black",
	"Tier1_GripPod_Tan",
	"Tier1_GripPod_MLOK_Black",
	"Tier1_GripPod_MLOK_Tan",
	"Tier1_AFG_MLOK_FDE",
	"Tier1_AFG_MLOK_Black",
	"Tier1_MVG_MLOK_FDE",
	"Tier1_MVG_MLOK_Black",
	"Tier1_BCM_Gunfighter_VG_FDE",
	"Tier1_BCM_Gunfighter_VG_Black",
	"Tier1_DD_MLOK_VFG_FDE",
	"Tier1_DD_MLOK_VFG_Black",
	"Tier1_RVG_MLOK_FDE",
	"Tier1_RVG_MLOK_Black",
	"Tier1_DD_MLOK_VFG_Black",
	"Tier1_DD_MLOK_VFG_FDE",
	"Tier1_KAC_VFG_MLOK_Black",
	"Tier1_KAC_VFG_MLOK_DE",
	"Tier1_SCAR_LA5_Top",
	"Tier1_SCAR_LA5_Side",
	"Tier1_SCAR_LA5_M300C",
	"Tier1_SCAR_LA5_M300C_FL",
	"Tier1_SCAR_LA5_M300C_Black",
	"Tier1_SCAR_LA5_M300C_Black_FL",
	"Tier1_SCAR_LA5_M600V",
	"Tier1_SCAR_LA5_M600V_FL",
	"Tier1_SCAR_LA5_M600V_Black",
	"Tier1_SCAR_LA5_M600V_Black_FL",
	"Tier1_SCAR_LA5_M603V",
	"Tier1_SCAR_LA5_M603V_FL",
	"Tier1_SCAR_NGAL_Top",
	"Tier1_SCAR_NGAL_Side",
	"Tier1_SCAR_NGAL_M300C",
	"Tier1_SCAR_NGAL_M300C_FL",
	"Tier1_SCAR_NGAL_M300C_Black",
	"Tier1_SCAR_NGAL_M300C_Black_FL",
	"Tier1_SCAR_NGAL_M600V",
	"Tier1_SCAR_NGAL_M600V_FL",
	"Tier1_SCAR_NGAL_M600V_Black",
	"Tier1_SCAR_NGAL_M600V_Black_FL",
	"Tier1_SCAR_NGAL_M603V",
	"Tier1_SCAR_NGAL_M603V_FL"

];
_blackfootWeaponsAndAmmo = [

];
_miscAce = [
	"murshun_cigs_cigpack",
	"murshun_cigs_lighter",
	"ACE_HuntIR_monitor",
	"ACE_RangeTable_82mm",
	"ACE_artilleryTable",
	"acex_intelitems_notepad",
	"ACE_SpareBarrel",
	"ACE_key_lockpick",
	"ACE_key_west",
	"rhsusf_bino_m24_ARD",
	"ItemMap",
	"ItemCompass",
	"ATM_ALTIMETER",
	"ACRE_PRC343",
	"ACE_CableTie",
	"ACE_Chemlight_Shield",
	"ACE_EarPlugs",
	"ACE_EntrenchingTool",
	"ACE_Fortify",
	"ACE_Flashlight_MX991",
	"ItemAndroid",
	"ItemcTabHCam",
	"ACE_IR_Strobe_Item",
	"ACE_Flashlight_XL50",
	"ACE_MapTools",
	"ACE_microDAGR",
	"ACE_SpraypaintBlack",
	"ACE_SpraypaintBlue",
	"ACE_SpraypaintGreen",
	"ACE_SpraypaintRed",
	"ACE_wirecutter",
	"Laserbatteries",
	"ACRE_VHF30108SPIKE",
	"ACRE_VHF30108MAST",
	"nzf_headbag_inventory"
];




